=== Dima252/GuessMarket/testing_files/EX1/GM-EX1-Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 (http://www.altova.com) by mazuki (darksiderg) -->
<!--W3C Schema generated by XMLSpy v2008 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="id" type="xs:int"/>
	<xs:element name="description" type="xs:string"/>
	<xs:element name="comision">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:int">
					<xs:attribute name="type" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="on-close"/>
								<xs:enumeration value="on-purchase"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="b" type="xs:int"/>
	<xs:element name="Guess-Market">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="GM-events"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GM-options">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="GM-option" maxOccurs="2"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GM-option" type="xs:string"/>
	<xs:element name="GM-method">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="GM-LMSR"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GM-events">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="GM-event" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GM-event">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="id"/>
				<xs:element ref="description"/>
				<xs:element ref="comision"/>
				<xs:element ref="GM-options"/>
				<xs:element ref="GM-method"/>
			</xs:sequence>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:list itemType="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="GM-LMSR">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="b"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Dima252/GuessMarket/testing_files/EX1/single.xml
<?xml version="1.0" encoding="UTF-8"?>
<Guess-Market xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="GM-EX1-schema.xsd">
	<GM-events>
		<GM-event name="Earth Quake on Dead Sea">
			<id>3</id>
			<description>Will there be an earth quake at the dead sea until December 31th 2026</description>
			<comision type="on-purchase">50</comision>
			<GM-options>
				<GM-option>Yes</GM-option>
				<GM-option>No</GM-option>
			</GM-options>
			<GM-method>
				<GM-LMSR>
					<b>100</b>
				</GM-LMSR>
			</GM-method>
		</GM-event>
	</GM-events>
</Guess-Market>
